import Head from "next/head";
import { DatePicker } from "antd";
import { Banner } from "../components/HomeComponents/Banner";
import HomeMain from "../components/Home/HomeMain";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <h4>Hello header</h4>
         <HomeMain/>
        </header>
        <div className="container mx-auto px-8 md:px-0 ">
           

          
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
